name: Generate and Deploy Drift Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies from file
        run: |
          ${{ steps.setup-python.outputs.python-path }} -m pip install --upgrade pip
          ${{ steps.setup-python.outputs.python-path }} -m pip install -r deployment/requirements_monitor.txt
    
      - name: List Installed Packages
        run: ${{ steps.setup-python.outputs.python-path }} -m pip list

      - name: Show Evidently Location
        run: ${{ steps.setup-python.outputs.python-path }} -m pip show evidently

      - name: Verify Evidently Installation
        run: |
          echo "Attempting to import Evidently modules..."
          ${{ steps.setup-python.outputs.python-path }} -c "from evidently.report import Report; print('Import Report OK')"
          ${{ steps.setup-python.outputs.python-path }} -c "from evidently.metric_preset import DataDriftPreset; print('Import DataDriftPreset OK')"
          echo "Evidently import verification complete."

      - name: Run Drift Monitor Script
        env:
          SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}
        run: |
          ${{ steps.setup-python.outputs.python-path }} deployment/drift_monitor.py

      - name: Commit and Push Drift Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages || echo "No gh-pages branch yet"
          git checkout gh-pages || git checkout --orphan gh-pages
          mkdir -p public
          cp -r ../public/* ./public/ 2>/dev/null || true
          git add public/drift_report.html public/drift_status.json || echo "No files to add"
          git commit -m "Actualizar reporte de drift [skip ci]" || echo "No changes to commit"
          git push origin gh-pages || echo "No gh-pages branch yet"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
