name: Generate and Deploy Drift Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies from file
        run: |
          ${{ steps.setup-python.outputs.python-path }} -m pip install --upgrade pip
          ${{ steps.setup-python.outputs.python-path }} -m pip install -r deployment/requirements_monitor.txt
    
      - name: List Installed Packages
        run: ${{ steps.setup-python.outputs.python-path }} -m pip list

      - name: Run Drift Monitor Script
        env:
          SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}
        run: |
          mkdir -p public
          ${{ steps.setup-python.outputs.python-path }} deployment/drift_monitor.py
          echo "Contenido de public después del script:"
          ls -la public

      - name: Ensure Drift Files Exist
        run: |
          if [ ! -f "public/drift_report.html" ]; then
            echo "⚠️ Archivo public/drift_report.html no encontrado"
            exit 1
          fi
          if [ ! -f "public/drift_status.json" ]; then
            echo "{}" > public/drift_status.json
            echo "⚠️ Archivo drift_status.json no encontrado, se creó uno vacío para el deploy"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
