name: Generate and Deploy Drift Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Matches the log

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Keep verbose install for now
          pip install --force-reinstall --no-cache-dir -vvv pandas psycopg2-binary evidently

      - name: List Installed Packages
        run: pip list

      # --- ADD STEP 1: Show Evidently Install Location ---
      - name: Show Evidently Location
        run: pip show evidently
      # --------------------------------------------------

      # --- ADD STEP 2: Show Python sys.path ---
      - name: Show Python Path
        run: python -c "import sys; print(sys.path)"
      # ----------------------------------------

      - name: Verify Evidently Installation # Keep this step
        run: |
          echo "Attempting to import Evidently modules..."
          python -c "from evidently.report import Report; print('Import Report OK')"
          python -c "from evidently.metric_preset import DataDriftPreset; print('Import DataDriftPreset OK')"
          echo "Evidently import verification complete."

      - name: Run Drift Monitor Script
        # ... (rest of the workflow) ...
      # ... (Deploy step) ...
        env:
          SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}
        run: |
          python deployment/drift_monitor.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public