name: Generate and Deploy Drift Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      
      - name: Install Dependencies from file
        run: |
          ${{ steps.setup-python.outputs.python-path }} -m pip install --upgrade pip
          # Instalar usando el archivo específico
          ${{ steps.setup-python.outputs.python-path }} -m pip install -r deployment/requirements_monitor.txt
    
      - name: List Installed Packages
        run: ${{ steps.setup-python.outputs.python-path }} -m pip list

      - name: Show Evidently Location
        run: ${{ steps.setup-python.outputs.python-path }} -m pip show evidently

      - name: Show Python Path
        run: ${{ steps.setup-python.outputs.python-path }} -c "import sys; print(sys.path)"

      - name: Verify Evidently Installation
        run: |
          echo "Attempting to import Evidently modules..."
          ${{ steps.setup-python.outputs.python-path }} -c "from evidently.report import Report; print('Import Report OK')"
          ${{ steps.setup-python.outputs.python-path }} -c "from evidently.metric_preset import DataDriftPreset; print('Import DataDriftPreset OK')"
          echo "Evidently import verification complete."

      - name: Run Drift Monitor Script
        env:
          SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}
        run: |
          ${{ steps.setup-python.outputs.python-path }} deployment/drift_monitor.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public